# Generated by Django 5.2.15 on 2026-07-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_channel_id', models.CharField(max_length=30)),
                ('mirror_enabled', models.BooleanField(default=True)),
                ('bot_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='commandlog',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
