# Generated by Django 5.2.15 on 2026-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botconfiguration_commandlog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='PENDING', max_length=20),
        ),
    ]
