# Generated by Django 5.2.15 on 2026-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(max_length=30, unique=True)),
                ('command_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=30)),
                ('guild_id', models.CharField(blank=True, max_length=30)),
                ('channel_id', models.CharField(blank=True, max_length=30)),
                ('report_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
